/**
                    )               (        (     (           (
          *   )  ( /(          (    )\ )     )\ )  )\ )  *   ) )\ )
        ` )  /(  )\()) (       )\  (()/( (  (()/( (()/(` )  /((()/(
        ( )(_))((_)\  )\    (((_)  /(_)))\  /(_)) /(_))( )(_))/(_))
        (_(_())  _((_)((_)   )\___ (_)) ((_)(_))_ (_)) (_(_())(_))
        |_   _| | || || __| ((/ __|| _ \| __||   \|_ _||_   _|/ __|
          | |   | __ || _|   | (__ |   /| _| | |) || |   | |  \__ \
          |_|   |_||_||___|   \___||_|_\|___||___/|___|  |_|  |___/

================================================================================
                        TYPEAHED FUNCTIONALITY
================================================================================

                             Twitter Team
                           ----------------
                https://github.com/twitter/typeahead.js


                    Nick P - Integration With Bootstrap 3
                  -----------------------------------------
http://stackoverflow.com/questions/18059161/css-issue-on-twitter-typeahead-with-bootstrap-3


                Willie Wheeler - Suggestion Width Fix
              -----------------------------------------
http://stackoverflow.com/questions/17957513/extending-the-width-of-bootstrap-typeahead-to-match-input-field


================================================================================
                                    CSS
================================================================================

                        Chris Coyier - truncate
                      ---------------------------
        https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/


                    Marc McGee - center-vertically
                  ----------------------------------
http://foundation.zurb.com/forum/posts/22792-is-there-a-simple-method-of-centering-text-vertically


================================================================================
                                  JavaScript
================================================================================

                            Chris Pickett - findWithAttr
                          --------------------------------
https://stackoverflow.com/questions/7176908/how-to-get-index-of-object-by-its-property-in-javascript/34004613#34004613


================================================================================
                                SPECIAL THANKS
================================================================================

                        Patrick Gillespie - ASCII Art
                      ---------------------------------
                      http://patorjk.com/software/taag/

                           _______  _        ______
                          (  ___  )( (    /|(  __  \
                          | (   ) ||  \  ( || (  \  )
                          | (___) ||   \ | || |   ) |
                          |  ___  || (\ \) || |   | |
                          | (   ) || | \   || |   ) |
                          | )   ( || )  \  || (__/  )
                          |/     \||/    )_)(______/

         					   ME - Being Great!
                             ---------------------
                      https://github.com/christopher-taylor

 */
